# Generated by Django 2.2 on 2019-04-15 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='published_dae',
            new_name='published_data',
        ),
    ]
